app_name: search.api.ch.gov.uk
group: api
weight: 902
routes:
  1: ^/alphabetical-search/companies
  2: ^/alphabetical-search/companies/*
  3: ^/dissolved-search/companies
  4: ^/advanced-search/companies
  5: ^/disqualified-search/disqualified-officers
  6: ^/disqualified-search/delete
  7: ^/officers-search/officers
  8: ^/search/healthcheck
  9: ^/company-search/companies/*
  10: ^/test-pr*
