app_name: search.api.ch.gov.uk
group: api
weight: 902
routes:
  1: ^/alphabetical-search/companies
  2: ^/alphabetical-search/companies/*
  3: ^/alphabetical-search/companies/delete/*
  4: ^/dissolved-search/companies
  5: ^/advanced-search/companies
  6: ^/disqualified-search/disqualified-officers
  7: ^/disqualified-search/delete
  8: ^/officers-search/officers
  9: ^/search/healthcheck