app_name: search.api.ch.gov.uk
group: api
weight: 902
routes:
  1: ^/alphabetical-search/companies
  2: ^/alphabetical-search/companies/*
  3: ^/dissolved-search/companies
  4: ^/advanced-search/companies
  5: ^/search/healthcheck