package uk.gov.companieshouse.search.api.model.response;

public enum ResponseStatus {
    SEARCH_FOUND,
    SEARCH_NOT_FOUND,
    SEARCH_ERROR,
    SERVICE_UNAVAILABLE,
    REQUEST_PARAMETER_ERROR,
    UPSERT_ERROR,
    UPDATE_REQUEST_ERROR,
    DOCUMENT_UPSERTED,
    SIZE_PARAMETER_ERROR,
    ADVANCED_SIZE_PARAMETER_ERROR,
    DATE_FORMAT_ERROR,
    MAPPING_ERROR
}
